
services:
  my-prometheus:
    image: prom/prometheus
    container_name: my-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  my-tempo:
    image: grafana/tempo
    container_name: my-tempo
    restart: unless-stopped
    ports:
      - "3200:3200"
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo/tempo.yml
    command: [ "-config.file=/etc/tempo/tempo.yml" ]

  my-loki:
    image: grafana/loki:main
    container_name: my-loki
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
    - "3100:3100"
    - "3100:3100"
#  volumes:
#    - ./loki-config.yaml:/etc/loki/loki-config.yaml
#  restart: unless-stopped
  my-grafana:
    image: grafana/grafana
    container_name: my-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro  # Correct volume mapping
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password